package com.sidert.sidertmovil.database;

public interface EntitiesCommonsContants {

    String TIPO_SOLICITUD_INDIVIDUAL_ORIGINACION = "INDIVIDUAL_ORIGINACION";
    String TIPO_SOLICITUD_GRUPAL_ORIGINACION = "GRUPAL_ORIGINACION";
    String TIPO_SOLICITUD_INDIVIDUAL_RENOVACION = "INDIVIDUAL_RENOVACION";
    String TIPO_SOLICITUD_GRUPAL_RENOVACION = "GRUPAL_RENOVACION";

}
